export const BATCH_ROLLBACK = 'BATCH_ROLLBACK';
export const BATCH_TOP_PROPERTIES = 'BATCH_TOP_PROPERTIES';
export const BATCH_TOP_SERVICES = 'BATCH_TOP_SERVICES';
export const BATCH_TOP_AGENTS = 'BATCH_TOP_AGENTS';
